### ISSUE TITLE
Building examples 04-collision 

### ISSUE THREAD

**Issue by glanzkaiser** [JuliaAstroSim/AstroNbodySim.jl#10]
I want to ask, whether the build is successful or not, I do not know how to view it, I double click one of the file it just showing some GUIs that I do not comprehend.

It become 100%, but then there is Error warning. I have to wait almost 2 days.

![Capture d’écran_2022-07-22_20-07-52](https://user-images.githubusercontent.com/72222484/180448393-97920fac-2db1-4fce-bb4b-cd6e2de0c236.png)
![Capture d’écran_2022-07-22_20-07-37](https://user-images.githubusercontent.com/72222484/180448410-7595bfdf-fd2b-446a-bd84-04715eb62b00.png)
![Capture d’écran_2022-07-22_20-08-12](https://user-images.githubusercontent.com/72222484/180448420-433e2d15-d266-4210-9345-e2dea92c7ade.png)

**Comment by islent** [comment]
The error came from `Makie`, can you find your version of `GLMakie`?

> whether the build is successful or not

The simulation job of `AstroNbodySim` has been finished (snapshots are successfully generated). 

> I do not know how to view it, I double click one of the file it just showing some GUIs that I do not comprehend.

Next step is visualization by `AstroPlot`. Snapshot files is in `Gadget2` (binary) format by default. You can copy and paste lines below `run(gpu)` to skip to visualization procedures.

It seems that you are not familiar with astrophysical scientific computing. I suggest [https://wwwmpa.mpa-garching.mpg.de/gadget/](https://wwwmpa.mpa-garching.mpg.de/gadget/) and papers therein.

> I have to wait almost 2 days

It takes less than one hour on a RTX4000 GPU.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/31057826/180586062-33cdd52c-937d-4136-bd6d-1d953f32c0e8.png">

**Comment by islent** [comment]
Cannot reproduce your problem. Maybe there is incompatibility in the version of `Makie` you are using.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/31057826/180587270-fcc94c06-46ce-48fb-989a-1d641631d38d.png">

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/31057826/180587300-13421c1a-9c25-452e-8d2e-d52331e976e6.png">

**Comment by glanzkaiser** [comment]
Your GPU is one high-end no wonder it can compile very fast. 

My Makie version( I add Makie just now, it seems it hasn't been added before on this environment):
![Capture d’écran_2022-07-23_20-45-19](https://user-images.githubusercontent.com/72222484/180607735-206cb3c0-098a-4d48-9745-1f55ea999aa9.png)


> Next step is visualization by AstroPlot. Snapshot files is in Gadget2 (binary) format by default. You can copy and paste lines below run(gpu) to skip to visualization procedures.

I try the code below `run(gpu):
```
plot_positionslice(gpu.config.output.dir, "snapshot_", collect(0:100), ".gadget2", gadget2(),
	dpi = 300, resolution =(400,400),
	xlims = (-200.0, +200.0), ylims = (-200.0, +200.0),
	times = collect(0.0:0.03:3.0) * u"Gyr",
	collection = DISK,
	markersize = 2.0,
	)
```

It produces an error (tried with cpu.config.output.dir too and still can't work.
![Capture d’écran_2022-07-23_20-36-20](https://user-images.githubusercontent.com/72222484/180607423-6aa534de-5937-4515-af61-855059631333.png)


> It seems that you are not familiar with astrophysical scientific computing. I suggest https://wwwmpa.mpa-garching.mpg.de/gadget/ and papers therein.

Yes, I am not familiar. Alright then I will see and read.

**Comment by islent** [comment]
> It produces an error (tried with cpu.config.output.dir too and still can't work.

That should not blame at `AstroNbodySim`. The error of `@u_str not defined` is telling you that `u"` string is not defined in your current work space. To solve it, you have to import `Unitful` package:
```julia
using Unitful, UnitfulAstro
using Distributed
using PhysicalParticles
using AstroIC, AstroIO
using AstroNbodySim
using AstroPlot
using GLMakie
using FFMPEG
using Printf
```

**Comment by glanzkaiser** [comment]
AAfter 3 days to recompile example 4 I finally get the pngs.

Wow, great.. how to create a gif out of this?

Thanks a lot. 

![Capture d’écran_2022-07-27_03-20-16](https://user-images.githubusercontent.com/72222484/181105307-a3c3799e-3aa4-4618-b8d5-78b0465760ba.png)

![Capture d’écran_2022-07-27_03-18-08](https://user-images.githubusercontent.com/72222484/181105295-f10f4a47-f1e8-4837-b845-2c5513d8ab52.png)
