### ISSUE TITLE
Initial Setup to AstroNbodySim

### ISSUE THREAD

**Issue by glanzkaiser** [JuliaAstroSim/AstroNbodySim.jl#9]
I create a new folder and start an environment for AstroNbodySim.jl

But, I cannot run the example/04-collisions/04-collisions.jl

I have added some packages:
Reexport v1.2.2..

then when I add `AstroIC` I get:

  **1 dependency successfully precompiled in 82 seconds (300 already precompiled, 2 skipped during auto due to previous errors)
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package**

Here is the screenshots:
![Capture d’écran_2022-07-19_15-30-03](https://user-images.githubusercontent.com/72222484/179709611-ea4c8afb-e0b2-4c62-8a1d-e756fd60c39b.png)

What should I do so I can run the collision example?

**Comment by islent** [comment]
Can you paste the output of calling `versioninfo`?

![image](https://user-images.githubusercontent.com/31057826/179728572-37d10790-a189-4fdb-8abc-940caa093b33.png)

By the way, I have the same problem of precompiling `AstroIC@v0.1`. However, it can be successfully imported.
![image](https://user-images.githubusercontent.com/31057826/179728503-fa04fd93-9024-4078-9587-ae87625a18f2.png)

Here's my suggestions of running `AstroNbodySim`:
- Install master branch of packages in `JuliaAstroSim`, because most of them are still under development. For example,
  ```
  pkg> add AstroIC#master
  ```
- Use `Julia v1.7.3` and above

**Comment by glanzkaiser** [comment]
I am not really an expert, still a newbie in Julia. So I am able to pass build AstroIC,

should I do `git clone https://github.com/JuliaAstroSim/AstroNbodySim.jl.git`
inside my working environment

![Capture d’écran_2022-07-20_21-24-36](https://user-images.githubusercontent.com/72222484/180006853-b222c8fd-fd8c-46fb-be03-06675ad738fb.png)


then what should I do?

**Comment by islent** [comment]
> should I do `git clone https://github.com/JuliaAstroSim/AstroNbodySim.jl.git` inside my working environment?

My suggestion is yes. Cloning a package does not much help running the package, but helps to search and understand source codes (if documentation is not well covered).

> then what should I do?

You can start from the documentation [https://juliaastrosim.github.io/AstroNbodySim.jl/dev/](https://juliaastrosim.github.io/AstroNbodySim.jl/dev/). Copy the raw codes, edit them, and run.

There is also a first user guide [https://juliaastrosim.github.io/AstroNbodySim.jl/dev/#First-Time-User-Guide](https://juliaastrosim.github.io/AstroNbodySim.jl/dev/#First-Time-User-Guide)

**Comment by glanzkaiser** [comment]
I already get it,

after I git clone `git clone https://github.com/JuliaAstroSim/AstroNbodySim.jl.git`
then at the directory I do
```
julia --project="."
julia> ]

pkg> build AstroIC
pkg> add AstroIC#master

julia> include("/../AstroNbodySim.jl/examples/install_pkgs.jl")

julia> include("/../AstroNbodySim.jl/examples/04-collisions/04-collisions.jl")
```

Then it said that I need CUDA. 

![Capture d’écran_2022-07-21_11-51-12](https://user-images.githubusercontent.com/72222484/180132665-b0a4764c-25ed-49ce-b886-f006ae984cb3.png)


I am installing CUDA from this link:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=18.04&target_type=deb_local

I want to know how to compile and install CUDA for the source tarball of CUDA, since I want to install CUDA on Linux OS (outside the commercial flags like Ubuntu, Fedora) made out of LFS book.

**Comment by islent** [comment]
>I want to know why we need to
`build AstroIC`
before
`add AstroIC#master`

This is not necessary. I was calling `build AstroIC` to trigger a fresh build of package, trying to find any error at build level. In daily usage, you can simply let `Pkg` automatically control building and precompiling procedures. All you need to do is, add a package, wait for building and precompiling, and `using` it.

> Then it said that I need CUDA.

About the installation of `CUDA`, see their instructions: [https://cuda.juliagpu.org/stable/installation/overview/](https://cuda.juliagpu.org/stable/installation/overview/)

`AstroNbodySim` can also run without CUDA. For example, in example-4, you can turn off GPU computing by setting `device = CPU()`

**Comment by glanzkaiser** [comment]
I think it works, with `device = CPU()`

But I have to wait 3 days. Hopefully in the future I can use CUDA so it will deliver the result faster. Simulating galaxy needs a lot of resources.

![Capture d’écran_2022-07-21_15-05-55](https://user-images.githubusercontent.com/72222484/180163072-379065d2-05e1-40af-a76b-bad442e046e4.png)


Thanks @islent
